# Generated by Django 5.0.1 on 2024-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pass_util', models.CharField(max_length=150)),
                ('mail_util', models.EmailField(max_length=254, verbose_name=True)),
            ],
        ),
    ]
